export const siteConfig = {
  name: "Arganis Nomad",
  whatsappName: "Arganis Nomad",
  phone: "+212634411760",
  whatsapp: "212634411760",
  email: "contact@arganisnomad.ma",
  googleRating: 4.9,
  reviewCount: 36,
  travelers: 300,
  responseTime: "2h",
};

export function getWhatsAppUrl(message?: string) {
  const base = `https://wa.me/${siteConfig.whatsapp}`;
  if (!message) return base;
  return `${base}?text=${encodeURIComponent(message)}`;
}

export const tourCardTextClasses = {
  title: "text-midnight",
  description: "text-midnight",
  muted: "text-midnight/85",
  price: "text-midnight",
} as const;

export const circuitCardTextClasses = tourCardTextClasses;

export const circuitDetailTextClasses = {
  title: "text-gold-light",
  description: "text-midnight",
  muted: "text-midnight/85",
  price: "text-midnight",
} as const;

export const excursionCardTextClasses = tourCardTextClasses;

export const excursionDetailTextClasses = {
  title: "text-gold-light",
  description: "text-midnight",
  muted: "text-midnight/85",
  price: "text-midnight",
} as const;

export const circuitsCatalog = [
  {
    id: "circuit-sahara-atlas-3j",
    slug: "marrakech-sahara-atlas-3-days",
    rating: 4.9,
    reviews: 56,
    price: 95,
    image: "/images/dest-merzouga-camp.jpg",
    images: [
      "/images/dest-marrakech-jemaa.jpg",
      "/images/dest-ait-benhaddou-oasis.jpg",
      "/images/dest-merzouga-camp.jpg",
      "/images/route-dades-gorges.jpg",
    ],
    badgeClass: "bg-terracotta",
    durationDays: 3,
    category: "desert",
    destination: "merzouga",
    difficulty: "moderate",
    departure: "marrakech",
  },
  {
    id: "sahara-dades-4j",
    slug: "sahara-dades-merzouga-4-day-tour",
    rating: 4.8,
    reviews: 62,
    price: 750,
    image: "/images/dest-merzouga-camp.jpg",
    images: [
      "/images/dest-ait-benhaddou.jpg",
      "/images/route-dades-gorges.jpg",
      "/images/dest-merzouga-camp.jpg",
      "/images/dest-ouarzazate.jpg",
    ],
    badgeClass: "bg-terracotta",
    durationDays: 4,
    category: "desert",
    destination: "merzouga",
    difficulty: "moderate",
    departure: "marrakech",
  },
  {
    id: "grand-tour-3j",
    slug: "marrakech-chefchaouen-3-days",
    rating: 4.9,
    reviews: 38,
    price: 450,
    image: "/images/dest-chefchaouen.jpg",
    images: [
      "/images/circuit-marrakech-koutoubia.jpg",
      "/images/circuit-casablanca-mosque.jpg",
      "/images/circuit-fes-tannery.jpg",
      "/images/dest-chefchaouen.jpg",
    ],
    durationDays: 3,
    category: "culture",
    destination: "chefchaouen",
    difficulty: "moderate",
    departure: "marrakech",
  },
  {
    id: "imperial-cities-8j",
    slug: "imperial-cities-8-day-fes-marrakech",
    rating: 4.8,
    reviews: 71,
    price: 1174,
    image: "/images/circuit-casablanca-mosque.jpg",
    images: [
      "/images/circuit-casablanca-mosque.jpg",
      "/images/dest-fes-fountain.jpg",
      "/images/dest-chefchaouen.jpg",
      "/images/dest-volubilis-mosaic.png",
    ],
    badgeClass: "bg-terracotta",
    durationDays: 8,
    category: "culture",
    destination: "imperial",
    difficulty: "easy",
    departure: "casablanca",
  },
  {
    id: "southern-coast-8j",
    slug: "taroudante-essaouira-8-day-southern-tour",
    rating: 4.8,
    reviews: 41,
    price: 1130,
    image: "/images/dest-essaouira-coast.jpg",
    images: [
      "/images/dest-ourika-argan.jpg",
      "/images/dest-agadir-beach.jpg",
      "/images/dest-essaouira-coast.jpg",
      "/images/dest-ait-benhaddou-oasis.jpg",
    ],
    durationDays: 8,
    category: "coast",
    destination: "essaouira",
    difficulty: "easy",
    departure: "marrakech",
  },
  {
    id: "megdaz-3j",
    slug: "vallee-megdaz-3-jours",
    rating: 4.9,
    reviews: 31,
    price: 420,
    image: "/images/dest-megdaz-valley.jpg",
    images: [
      "/images/dest-megdaz-valley.jpg",
      "/images/dest-megdaz-village.jpg",
      "/images/dest-megdaz-green-valley.jpg",
      "/images/dest-megdaz-tbourida.jpg",
    ],
    durationDays: 3,
    category: "adventure",
    destination: "atlas",
    difficulty: "moderate",
    departure: "marrakech",
  },
] as const;

export const excursionsCatalog = [
  {
    id: "ourika",
    slug: "ourika-valley-day-trip",
    rating: 4.8,
    reviews: 94,
    price: 72,
    image: "/images/dest-ourika-valley.jpg",
    images: [
      "/images/dest-ourika-valley.jpg",
      "/images/dest-ourika-waterfall.jpg",
      "/images/dest-ourika-river.jpg",
      "/images/dest-ourika-argan.jpg",
    ],
    badgeClass: "bg-oasis",
    durationDays: 1,
    category: "nature",
    difficulty: "moderate",
    departure: "marrakech",
    destination: "atlas",
  },
  {
    id: "agafay",
    slug: "agafay-desert-day-trip",
    rating: 4.9,
    reviews: 118,
    price: 40,
    flatPrice: true,
    image: "/images/exc-agafay-camel-trek.png",
    images: [
      "/images/exc-agafay-camel-trek.png",
      "/images/exc-agafay-camel-caravan.png",
      "/images/exc-agafay-luxury-cabana.png",
      "/images/exc-agafay-desert-camp.png",
    ],
    badgeClass: "bg-terracotta",
    durationDays: 1,
    category: "adventure",
    difficulty: "easy",
    departure: "marrakech",
    destination: "agafay",
  },
  {
    id: "imlil",
    slug: "imlil-toubkal-day-hike",
    rating: 4.9,
    reviews: 78,
    price: 84,
    image: "/images/dest-megdaz-atlas.jpg",
    images: [
      "/images/dest-megdaz-atlas.jpg",
      "/images/route-mountain-pass.png",
      "/images/dest-megdaz-valley.jpg",
      "/images/dest-megdaz-village.jpg",
    ],
    badgeClass: "bg-terracotta",
    durationDays: 1,
    category: "adventure",
    difficulty: "moderate",
    departure: "marrakech",
    destination: "atlas",
  },
  {
    id: "trois-vallees",
    slug: "trois-vallees-haut-atlas-4x4",
    rating: 4.8,
    reviews: 56,
    price: 102,
    image: "/images/dest-ourika-waterfall.jpg",
    images: [
      "/images/dest-ourika-valley.jpg",
      "/images/dest-ourika-waterfall.jpg",
      "/images/route-mountain-pass.png",
      "/images/dest-ourika-cascade.jpg",
    ],
    durationDays: 1,
    category: "nature",
    difficulty: "easy",
    departure: "marrakech",
    destination: "atlas",
  },
  {
    id: "ouzoud",
    slug: "cascades-ouzoud-day-trip",
    rating: 4.9,
    reviews: 112,
    price: 150,
    flatPrice: true,
    image: "/images/dest-ouzoud-falls.png",
    badgeClass: "bg-terracotta",
    durationDays: 1,
    category: "nature",
    difficulty: "easy",
    departure: "marrakech",
    destination: "ouzoud",
  },
  {
    id: "essaouira",
    slug: "essaouira-medina-day-trip",
    rating: 4.8,
    reviews: 103,
    price: 290,
    flatPrice: true,
    image: "/images/dest-essaouira-coast.jpg",
    durationDays: 1,
    category: "coast",
    difficulty: "easy",
    departure: "marrakech",
    destination: "essaouira",
  },
  {
    id: "ait-benhaddou",
    slug: "ait-benhaddou-ouarzazate-unesco-day-trip",
    rating: 4.9,
    reviews: 87,
    price: 300,
    flatPrice: true,
    image: "/images/dest-ait-benhaddou.jpg",
    images: [
      "/images/dest-ait-benhaddou.jpg",
      "/images/dest-ait-benhaddou-oasis.jpg",
      "/images/dest-kasbah-arches.jpg",
      "/images/route-tizi-ntichka.jpg",
    ],
    durationDays: 1,
    category: "culture",
    difficulty: "easy",
    departure: "marrakech",
    destination: "ouarzazate",
  },
  {
    id: "casablanca",
    slug: "casablanca-hassan-ii-day-trip",
    rating: 4.7,
    reviews: 45,
    price: 156,
    image: "/images/circuit-casablanca-mosque.jpg",
    images: [
      "/images/circuit-casablanca-mosque.jpg",
      "/images/circuit-casablanca-hassan-ii.jpg",
      "/images/dest-marrakech-medina.jpg",
      "/images/dest-marrakech-jemaa.jpg",
    ],
    durationDays: 1,
    category: "culture",
    difficulty: "easy",
    departure: "marrakech",
    destination: "casablanca",
  },
  {
    id: "agadir-taghazout",
    slug: "agadir-taghazout-surf-day-trip",
    rating: 4.8,
    reviews: 18,
    price: 125,
    image: "/images/dest-agadir-beach.jpg",
    images: [
      "/images/dest-agadir-beach.jpg",
      "/images/dest-essaouira-coast.jpg",
      "/images/dest-essaouira-ramparts.jpg",
      "/images/dest-essaouira-port.png",
    ],
    durationDays: 1,
    category: "coast",
    difficulty: "easy",
    departure: "marrakech",
    destination: "agadir",
  },
] as const;

export const fleetCatalog = [
  { id: "sedan", icon: "sedan" as const, seats: "1-3" },
  { id: "van", icon: "van" as const, seats: "4-7" },
  { id: "suv", icon: "suv" as const, seats: "1-4" },
  { id: "minibus", icon: "minibus" as const, seats: "8-17" },
] as const;

export const transfersCatalog = [
  {
    id: "airport",
    price: 18,
    image: "/images/transfer-marrakech-airport.jpg",
  },
  {
    id: "city",
    price: 15,
    image: "/images/dest-marrakech-souk.jpg",
  },
  {
    id: "intercity",
    price: 25,
    image: "/images/route-mountain-pass.png",
  },
  {
    id: "group",
    price: 32,
    image: "/images/fleet-van-desert.png",
  },
] as const;

export const galleryCatalog = [
  { id: "van-desert", image: "/images/fleet-van-desert.png" },
  { id: "vans-tunnel", image: "/images/fleet-vans-tunnel.png" },
  { id: "suv-kasbah", image: "/images/dest-kasbah-arches.jpg" },
  { id: "atlas-highway", image: "/images/route-atlas-highway.png" },
  { id: "mountain-pass", image: "/images/route-mountain-pass.png" },
  { id: "dades-gorges", image: "/images/route-dades-gorges.jpg" },
  { id: "ouzoud", image: "/images/dest-ouzoud-falls.png" },
  { id: "ourika", image: "/images/dest-ourika-valley.jpg" },
  { id: "essaouira", image: "/images/dest-essaouira-coast.jpg" },
  { id: "volubilis", image: "/images/dest-volubilis-arches.png" },
  { id: "desert-oasis", image: "/images/dest-merzouga-camp.jpg" },
  { id: "fes-tannery", image: "/images/dest-fes-fountain.jpg" },
  { id: "sunset", image: "/images/dest-sunset-lake.png" },
] as const;

export const HOME_PREVIEW_LIMIT = 4;

export const activitiesCatalog = [
  { id: "camel", price: 35, icon: "camel", image: "/images/dest-merzouga-dunes.jpg" },
  { id: "tent", price: 180, icon: "tent", image: "/images/dest-merzouga-camp.jpg" },
  { id: "balloon", price: 120, icon: "balloon", image: "/images/dest-marrakech-jemaa.jpg" },
  { id: "chef", price: 55, icon: "chef", image: "/images/dest-marrakech-souk.jpg" },
  { id: "sunset", price: 65, icon: "sunset", image: "/images/dest-sunset-lake.png" },
  { id: "spa", price: 70, icon: "spa", image: "/images/dest-morocco-plasterwork.jpg" },
  { id: "hiking", price: 30, icon: "hiking", image: "/images/dest-megdaz-valley.jpg" },
  { id: "quad", price: 60, icon: "quad", image: "/images/dest-desert-mesa.png" },
] as const;

export const destinationsCatalog = [
  {
    id: "marrakech",
    slug: "marrakech-imperial-city",
    count: 21,
    rating: 4.9,
    reviews: 186,
    price: 12,
    image: "/images/dest-marrakech-jemaa.jpg",
    images: [
      "/images/dest-marrakech-jemaa.jpg",
      "/images/dest-marrakech-medina.jpg",
      "/images/dest-marrakech-souk.jpg",
      "/images/dest-marrakech-night.jpg",
    ],
  },
  {
    id: "merzouga",
    slug: "merzouga-sahara-desert",
    count: 6,
    rating: 4.9,
    reviews: 142,
    price: 45,
    image: "/images/dest-merzouga-camp.jpg",
    images: [
      "/images/dest-merzouga-camp.jpg",
      "/images/dest-merzouga-dunes-clean.jpg",
      "/images/dest-merzouga-large-dune.jpg",
      "/images/dest-merzouga-erg-chebbi.jpg",
    ],
  },
  {
    id: "nord-maroc",
    slug: "northern-morocco-tangier-chefchaouen",
    count: 5,
    rating: 4.8,
    reviews: 67,
    price: 48,
    image: "/images/dest-chefchaouen.jpg",
    images: [
      "/images/dest-chefchaouen.jpg",
      "/images/dest-tangier-medina.jpg",
      "/images/dest-tangier-street.jpg",
      "/images/dest-cape-spartel.png",
    ],
  },
  {
    id: "fes",
    slug: "fes-imperial-medina",
    count: 5,
    rating: 4.9,
    reviews: 98,
    price: 19,
    image: "/images/dest-fes-tannery.png",
    images: [
      "/images/dest-fes-tannery.png",
      "/images/dest-fes-fountain.jpg",
      "/images/dest-morocco-plasterwork.jpg",
      "/images/dest-fes-medina.jpg",
    ],
  },
  {
    id: "essaouira",
    slug: "essaouira-atlantic-medina",
    count: 5,
    rating: 4.8,
    reviews: 103,
    price: 9,
    image: "/images/dest-essaouira-coast.jpg",
    images: [
      "/images/dest-essaouira-coast.jpg",
      "/images/dest-essaouira-medina.jpg",
      "/images/dest-essaouira-port.png",
      "/images/dest-essaouira-ramparts.jpg",
    ],
  },
  {
    id: "megdaz",
    slug: "megdaz-atlas-valley",
    count: 3,
    rating: 4.9,
    reviews: 31,
    price: 59,
    image: "/images/dest-megdaz-valley.jpg",
    images: [
      "/images/dest-megdaz-valley.jpg",
      "/images/dest-megdaz-village.jpg",
      "/images/dest-megdaz-green-valley.jpg",
      "/images/dest-megdaz-tbourida.jpg",
    ],
  },
  {
    id: "agadir",
    slug: "agadir-south-coast",
    count: 2,
    rating: 4.7,
    reviews: 45,
    price: 18,
    image: "/images/dest-agadir-beach.jpg",
  },
  {
    id: "oualili",
    slug: "oualili-volubilis-ruins",
    count: 8,
    rating: 4.9,
    reviews: 74,
    price: 35,
    image: "/images/dest-volubilis-mosaic.png",
    images: [
      "/images/dest-volubilis-mosaic.png",
      "/images/dest-volubilis-ruins.png",
      "/images/dest-volubilis-site.png",
      "/images/dest-volubilis-arches.png",
    ],
  },
] as const;

export const statsCatalog = [
  { value: 12, suffix: "+" },
  { value: 300, suffix: "+" },
  { value: 45, suffix: "+" },
  { value: 4.9, suffix: "/5" },
] as const;

export const testimonialsCatalog = [
  { id: "claire", name: "Claire Aufrechter" },
  { id: "adil", name: "Adil Kharbouch" },
  { id: "genevieve", name: "Geneviève Boutin" },
  { id: "salvatore", name: "Salvatore Ristagno" },
] as const;

export const featuresCatalog = [
  { id: "guides" },
  { id: "custom" },
  { id: "support" },
  { id: "tested" },
] as const;

export const navLinkIds = [
  "excursions",
  "circuits",
  "destinations",
  "activities",
  "transfers",
  "discover",
] as const;
